name: cheap
channels:
  - pytorch
  - conda-forge
  - nvidia
  - bioconda
  - salilab
dependencies:
  - python==3.10
  - pip
  - ihm
  - ninja
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - bioconda::tmalign
  - pip:
    - -r requirements.txt